# Generated by Django 5.0.6 on 2024-05-22 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_car_image_car_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('year', models.IntegerField(default=0)),
                ('genre', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('price', models.IntegerField(default=0)),
                ('director', models.CharField(max_length=100)),
                ('time', models.TimeField()),
                ('rating', models.IntegerField(default=0)),
                ('age', models.IntegerField(default=16)),
                ('operator', models.CharField(max_length=100)),
            ],
        ),
    ]
